config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

   authenticated :user do
    root 'home#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

  post 'conversations/read' => 'conversations#read'
  post 'search' => 'contacts#search', defaults: { format: 'js' }
  post 'add' => 'contacts#add', defaults: { format: 'js' }

  post 'contacts-request/handle' => 'contacts#handle'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user1, :foreign_key => :user1_id, class_name: 'User'
  belongs_to :user2, :foreign_key => :user2_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :user1_id, :scope => :user2_id

  scope :involving, -> (user) do
    where("conversations.user1_id =? OR conversations.user2_id =?",user.id,user.id)
  end

  scope :between, -> (user1_id,user2_id) do
    where("(conversations.user1_id = ? AND conversations.user2_id =?) OR (conversations.user1_id = ? AND conversations.user2_id =?)", user1_id,user2_id, user2_id, user1_id)
  end

  

  def unread_msg_count (recipient_id)
    self.messages.where("read=? AND recipient_id=?",false, recipient_id).count
  end

  def unread_messages
    self.messages.where("read=?",false)
  end

  def read_messages!
    self.unread_messages.update_all(read: true)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  layout false
  # Creates conversation box
  def create
    if Conversation.between(params[:user1_id],params[:user2_id]).present?
      @conversation = Conversation.between(params[:user1_id],params[:user2_id]).first
      # @messages = @conversation.messages.where(read:false).update_all(read: true) # maybe change
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @receiver = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  def read
    @conversation = Conversation.find(params[:conversation_id])
    if @conversation.unread_messages.any?
      @conversation.read_messages!
    end
    render :nothing => true
  end

  private
  def conversation_params
    params.permit(:user1_id, :user2_id)
  end

  def interlocutor(conversation)
    current_user == conversation.user2 ? conversation.user1 : conversation.user2
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @receiver.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='material-icons'>chat_bubble_outline</i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='material-icons'>clear</i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <div class="actions">
    <button class="btn waves-effect waves-light submitMsg" type="submit" name="action">Send
      <i class="material-icons right">send</i>
    </button>
  </div>    
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation)+"/#{current_user.id}" %>